### ISSUE TITLE
Unable to whitelist hilton.com

### ISSUE THREAD

**Issue by getgray** [stevejenkins/postwhite#62]
Hilton Hotels reservations sends emails and I've not been able to get them through postscreen (postwhite).  I have them in my postwhite.conf file's custom hosts as hilton.com and through digging I saw maybe mail.hiltonres.com was a source.  I added "sparkpost.com" as I saw it in there, too.  

Sample IP's that have been rejected are 137.22.228.7 and 137.22.225.129.  I've manually whitelisted these examples, but it seems every time I get a new connection from them it's from a different one, or pool.  

I've dug in SPF records unable to find these IP address,   Surely someone as big as Hilton has their SPF records correct.  Or not. 

Can anyone assist me in determining how to find their sending IP's SPF's so I can add what to lookup to postwhite?  Assuming a SPF record exists.

**Comment by alainwolf** [comment]
[hilton.com is using microsoft](https://www.hardenize.com/report/hilton.com/1725789975#email) for their mail and has set their SPF and DMARC accordingly.

The two IPs you mention are both belonging to [braze.com](https://www.braze.com/company) a "customer engagement platform".
You can't find that out easy using `whois` which returns `137.22.224.0/19`.

These kind of setups, usually use a subdomain for transactional or other specialized emails. The subdomain then should have it's own SPF and DMARC setup.

Why not ask Hilton? Since postwhite is probably behaving as designed.

**Comment by getgray** [comment]
Thank you.  I was erroneously trying to use dig.  That should cure me.

**Comment by getgray** [comment]
Thank you. I was erroneously trying to use dig. That should cure me.
